# Generated by Django 5.0.1 on 2025-05-19 12:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EnergyLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="记录时间"
                    ),
                ),
                ("energy_level", models.CharField(max_length=50, verbose_name="精力水平")),
                (
                    "current_activity_type",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="当前活动类型"
                    ),
                ),
            ],
            options={
                "verbose_name": "精力日志",
                "verbose_name_plural": "精力日志",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="LongTermGoal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(verbose_name="长期目标描述")),
                (
                    "status",
                    models.CharField(
                        choices=[("持续追求", "持续追求"), ("已归档", "已归档")],
                        default="持续追求",
                        max_length=50,
                        verbose_name="目标状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "长期目标",
                "verbose_name_plural": "长期目标清单",
            },
        ),
        migrations.CreateModel(
            name="ShortTermGoal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(verbose_name="短期目标描述")),
                (
                    "target_date",
                    models.DateField(blank=True, null=True, verbose_name="目标完成日期"),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("重要且紧急", "重要且紧急"),
                            ("重要不紧急", "重要不紧急"),
                            ("紧急不重要", "紧急不重要"),
                            ("不重要不紧急", "不重要不紧急"),
                        ],
                        default="重要不紧急",
                        max_length=50,
                        verbose_name="优先级",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("未开始", "未开始"),
                            ("进行中", "进行中"),
                            ("已完成", "已完成"),
                            ("已推迟", "已推迟"),
                            ("已放弃", "已放弃"),
                            ("阻塞", "阻塞"),
                        ],
                        default="未开始",
                        max_length=50,
                        verbose_name="目标状态",
                    ),
                ),
                (
                    "completion_date",
                    models.DateField(blank=True, null=True, verbose_name="实际完成日期"),
                ),
                (
                    "estimated_time_days",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="预估天数"
                    ),
                ),
                (
                    "actual_time_days",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="实际天数"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "短期目标",
                "verbose_name_plural": "短期目标清单",
            },
        ),
        migrations.CreateModel(
            name="WorkLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_name", models.CharField(max_length=255, verbose_name="任务名称")),
                (
                    "task_source",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="任务来源"
                    ),
                ),
                ("timestamp_start", models.DateTimeField(verbose_name="会话开始时间")),
                ("timestamp_end", models.DateTimeField(verbose_name="会话结束时间")),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(verbose_name="会话时长(分钟)"),
                ),
                (
                    "user_reported_status_at_end",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="用户报告的结束状态"
                    ),
                ),
                (
                    "energy_cost",
                    models.CharField(
                        blank=True,
                        choices=[("高", "高"), ("中", "中"), ("低", "低"), ("", "未设置")],
                        max_length=10,
                        null=True,
                        verbose_name="精力消耗评估",
                    ),
                ),
                (
                    "tags",
                    models.TextField(blank=True, null=True, verbose_name="相关标签 (快照)"),
                ),
                (
                    "logged_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="日志记录时间"),
                ),
            ],
            options={
                "verbose_name": "工作日志",
                "verbose_name_plural": "工作日志",
                "ordering": ["-timestamp_start"],
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="任务名称")),
                (
                    "priority",
                    models.PositiveIntegerField(
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                        default=3,
                        verbose_name="优先级(1-5,小优先)",
                    ),
                ),
                (
                    "energy_level_estimate",
                    models.CharField(
                        blank=True,
                        choices=[("高", "高"), ("中", "中"), ("低", "低"), ("", "未设置")],
                        default="",
                        max_length=10,
                        verbose_name="精力预估",
                    ),
                ),
                ("tags", models.TextField(blank=True, verbose_name="标签 (逗号分隔)")),
                (
                    "estimated_time_minutes",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="预估分钟数"
                    ),
                ),
                (
                    "actual_time_minutes",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="实际分钟数"
                    ),
                ),
                (
                    "start_date",
                    models.DateField(blank=True, null=True, verbose_name="计划开始日期"),
                ),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="计划截止日期"),
                ),
                (
                    "completion_date",
                    models.DateField(blank=True, null=True, verbose_name="实际完成日期"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("未开始", "未开始"),
                            ("进行中", "进行中"),
                            ("已完成", "已完成"),
                            ("等待中", "等待中"),
                            ("已推迟", "已推迟"),
                            ("已取消", "已取消"),
                            ("阻塞", "阻塞"),
                        ],
                        default="未开始",
                        max_length=50,
                        verbose_name="任务状态",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="任务类型 (临时)"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "long_term_goal_ref",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tasks",
                        to="core.longtermgoal",
                        verbose_name="关联的长期目标",
                    ),
                ),
                (
                    "short_term_goal_ref",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tasks",
                        to="core.shorttermgoal",
                        verbose_name="关联的短期目标",
                    ),
                ),
            ],
            options={
                "verbose_name": "任务",
                "verbose_name_plural": "任务清单",
                "ordering": ["priority", "end_date", "name"],
            },
        ),
    ]
