# Generated by Django 5.0.1 on 2025-05-20 04:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_usersetting_alter_energylog_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="actual_time_minutes",
            field=models.PositiveIntegerField(default=0, verbose_name="实际分钟数"),
        ),
    ]
